# Generated by Django 6.0.7 on 2026-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default='S1', max_length=20),
        ),
    ]
