# Generated by Django 6.0.7 on 2026-09-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_subject_credits_subject_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester']},
        ),
    ]
