# Generated by Django 6.0.7 on 2026-09-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='college.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('subject', 'student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
    ]
