# Generated by Django 6.0.7 on 2026-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_enrollment_subject_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
