# Generated by Django 6.0.7 on 2026-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_name', 'department'), name='unique_course_per_department'),
        ),
    ]
