# Generated by Django 6.0.7 on 2026-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_course_unique_course_per_department'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('course', 'subject_name'), name='unique_subject_per_course'),
        ),
    ]
