# Generated by Django 6.0.7 on 2026-09-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
