# Generated by Django 6.0.7 on 2026-09-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_studentfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='amount_due',
        ),
    ]
