# Generated by Django 6.0.7 on 2026-09-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_remove_studentfee_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='status',
        ),
    ]
