# Generated by Django 6.0.7 on 2026-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_remove_studentfee_amount_paid_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/user-default.jpg', upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/user-default.jpg', upload_to='profile_photos/'),
        ),
    ]
